parc_info_homepage:
    path:     /
    defaults: { _controller: ParcInfoBundle:Default:index }

parc_info_ajouter:
    path:     /ajouter
    defaults: { _controller: ParcInfoBundle:Default:ajouter }
    
    
parc_info_rechercher:
    path:     /search
    defaults: { _controller: ParcInfoBundle:Default:rechercher }
    
parc_info_matHS:
    path:     /matHS
    defaults: { _controller: ParcInfoBundle:Default:matHS }
    
parc_info_matPG:
    path:     /matPG
    defaults: { _controller: ParcInfoBundle:Default:matPG }
    
parc_info_edition:
    path:     /edition
    defaults: { _controller: ParcInfoBundle:Default:edition }
    
parc_info_etat:
    path:     /etat/{numSite}/{idEtat}
    defaults: { _controller: ParcInfoBundle:Default:etat }
    
parc_info_fiche:
    path:     /fiche/{idmat}
    defaults: { _controller: ParcInfoBundle:Default:fiche }
    
parc_info_matEnPanne:
    path:     /matEnPanne
    defaults: { _controller: ParcInfoBundle:Default:matEnPanne }
    
    